---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    #run_list:
    #  - recipe[apt]

  #- name: centos-6.5
    #run_list:
    #  - recipe[yum]

suites:
  - name: tomcat_providers
    run_list:
      - recipe[tomcat::base]
      - recipe[tomcat_test_providers]
    attributes:
      java:
        install_flavor: "oracle"
        jdk_version: "7"
        oracle:
          accept_oracle_download_terms: true
